Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 552, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
az.plot_kde(rhos[1][:,0,1], bw=2);
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/tmp/ipykernel_2439/3075958100.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0maz[0m[0;34m.[0m[0mplot_kde[0m[0;34m([0m[0mrhos[0m[0;34m[[0m[0;36m1[0m[0;34m][0m[0;34m[[0m[0;34m:[0m[0;34m,[0m[0;36m0[0m[0;34m,[0m[0;36m1[0m[0;34m][0m[0;34m,[0m [0mbw[0m[0;34m=[0m[0;36m2[0m[0;34m)[0m[0;34m;[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/arviz/plots/kdeplot.py[0m in [0;36mplot_kde[0;34m(values, values2, cumulative, rug, label, bw, adaptive, quantiles, rotated, contour, hdi_probs, fill_last, figsize, textsize, plot_kwargs, fill_kwargs, rug_kwargs, contour_kwargs, contourf_kwargs, pcolormesh_kwargs, is_circular, ax, legend, backend, backend_kwargs, show, return_glyph, **kwargs)[0m
[1;32m    259[0m                 [0mbw[0m [0;34m=[0m [0;34m"experimental"[0m[0;34m[0m[0;34m[0m[0m
[1;32m    260[0m [0;34m[0m[0m
[0;32m--> 261[0;31m         [0mgrid[0m[0;34m,[0m [0mdensity[0m [0;34m=[0m [0mkde[0m[0;34m([0m[0mvalues[0m[0;34m,[0m [0mis_circular[0m[0;34m,[0m [0mbw[0m[0;34m=[0m[0mbw[0m[0;34m,[0m [0madaptive[0m[0;34m=[0m[0madaptive[0m[0;34m,[0m [0mcumulative[0m[0;34m=[0m[0mcumulative[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    262[0m         [0mlower[0m[0;34m,[0m [0mupper[0m [0;34m=[0m [0mgrid[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m [0mgrid[0m[0;34m[[0m[0;34m-[0m[0;36m1[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m    263[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/arviz/stats/density_utils.py[0m in [0;36mkde[0;34m(x, circular, **kwargs)[0m
[1;32m    478[0m     """
[1;32m    479[0m     [0mx[0m [0;34m=[0m [0mx[0m[0;34m[[0m[0mnp[0m[0;34m.[0m[0misfinite[0m[0;34m([0m[0mx[0m[0;34m)[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 480[0;31m     [0;32mif[0m [0mx[0m[0;34m.[0m[0msize[0m [0;34m==[0m [0;36m0[0m [0;32mor[0m [0mnp[0m[0;34m.[0m[0mall[0m[0;34m([0m[0mx[0m [0;34m==[0m [0mx[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    481[0m         [0mwarnings[0m[0;34m.[0m[0mwarn[0m[0;34m([0m[0;34m"Your data appears to have a single value or no finite values"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    482[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/tensorflow/python/framework/ops.py[0m in [0;36m__getattr__[0;34m(self, name)[0m
[1;32m    439[0m         [0mIf[0m [0myou[0m [0mare[0m [0mlooking[0m [0;32mfor[0m [0mnumpy[0m[0;34m-[0m[0mrelated[0m [0mmethods[0m[0;34m,[0m [0mplease[0m [0mrun[0m [0mthe[0m [0mfollowing[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    440[0m         [0;32mfrom[0m [0mtensorflow[0m[0;34m.[0m[0mpython[0m[0;34m.[0m[0mops[0m[0;34m.[0m[0mnumpy_ops[0m [0;32mimport[0m [0mnp_config[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 441[0;31m         np_config.enable_numpy_behavior()""".format(type(self).__name__, name))
[0m[1;32m    442[0m     [0mself[0m[0;34m.[0m[0m__getattribute__[0m[0;34m([0m[0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    443[0m [0;34m[0m[0m

[0;31mAttributeError[0m: 
        'EagerTensor' object has no attribute 'size'.
        If you are looking for numpy-related methods, please run the following:
        from tensorflow.python.ops.numpy_ops import np_config
        np_config.enable_numpy_behavior()
AttributeError: 
        'EagerTensor' object has no attribute 'size'.
        If you are looking for numpy-related methods, please run the following:
        from tensorflow.python.ops.numpy_ops import np_config
        np_config.enable_numpy_behavior()

